# Input series column names
UNEMPLOYMENT_RATE = "Unemployment_Rate"
HIGH_YIELD_SPREAD = "High_Yield_Spread"
FINANCIAL_STRESS_INDEX = "Financial_Stress_Index"
YIELD_SPREAD_10Y3M = "Yield_Spread_10Y3M"
SAHM_RULE_INDICATOR = "Sahm_Rule_Indicator"

# Alert columns
INVERTED_CURVE = "INVERTED_CURVE"
FINANCIAL_STRESS = "FINANCIAL_STRESS"

# Market alert columns
SP500_DEATH_CROSS = "SP500_DEATH_CROSS"
SP500_DEATH_CROSS_ACTIVE = "SP500_DEATH_CROSS_ACTIVE"
SP500_CONFIRMED_DEATH_CROSS = "SP500_CONFIRMED_DEATH_CROSS"
SP500_SMA_RATIO = "SP500_SMA_RATIO"
