# Catalog codes (dataframe column names match catalog codes for FRED series)
UNEMPLOYMENT_RATE = "Unemployment_Rate"
HIGH_YIELD_SPREAD = "High_Yield_Spread"
FINANCIAL_STRESS_INDEX = "Financial_Stress_Index"
YIELD_SPREAD_10Y3M = "Yield_Spread_10Y3M"
REAL_INTEREST_RATES = "Real_Interest_Rates"
BREAKEVEN_INFLATION = "Breakeven_Inflation"
TREASURY_10Y_YIELD = "Treasury_10Y_Yield"
BROAD_DOLLAR_INDEX = "Broad_Dollar_Index"
RESERVE_BALANCES = "Reserve_Balances"
OVERNIGHT_RRP = "Overnight_RRP"
SOFR = "SOFR"
SP500_DEATH_CROSS = "SP500_Death_Cross"
